#!/usr/bin/env python3

# stdlib
import sys
import argparse

# 3rd-party
import rospkg
import rospy
from colorama import Fore, Style
from std_msgs.msg import Header, ColorRGBA
from geometry_msgs.msg import Point
from gazebo_msgs.msg import ModelState, ModelStates
from geometry_msgs.msg import Point, Pose, Vector3, Quaternion
from interactive_markers.interactive_marker_server import *
from interactive_markers.menu_handler import *
from visualization_msgs.msg import *
from atom_core.ros_utils import filterLaunchArguments
from gazebo_msgs.srv import SetModelState, GetModelState, GetModelStateRequest, SetModelStateRequest
from tf2_ros import TransformBroadcaster
from localbot_core.src.interactive_data_collection import InteractiveDataCollection
from localbot_core.src.automatic_data_collection import AutomaticDataCollection

# not needed here I guess
#rospy.init_node("interactive_camera")



def main():
    
    ### BIG IF ###
    
    # get argument from launch file
    
    rospy.init_node("interactive_data_collection")
    
    # InteractiveDataCollection(model_name='localbot')
    InteractiveDataCollection(model_name='localbot')
    
    
    rospy.spin() # in interactive
    # rate.sleep() # in automatic


if __name__ == "__main__":
    main()



