#!/usr/bin/env python3

# stdlib
import sys
import argparse
import copy

# 3rd-party
import rospy
from colorama import Fore, Style
from std_msgs.msg import Header
from geometry_msgs.msg import Point, Pose, Vector3, Quaternion, TransformStamped, Transform
from visualization_msgs.msg import *
from localbot_localization.src.dataset import LocalBotDataset
from localbot_localization.src.validate_dataset import ValidateDataset
import numpy as np
import os

def main():    
    parser = argparse.ArgumentParser(description='Validate dataset')
    parser.add_argument('-f', '--folder', type=str, required=True, help='Name of the dataset')

    
    arglist = [x for x in sys.argv[1:] if not x.startswith('__')]
    args = vars(parser.parse_args(args=arglist))
    
    folder = args['folder']
    size_dataset = sum(f.endswith('.png') for f in os.listdir(folder))
    
    for idx in range(size_dataset):
        os.rename(f'{folder}/{idx:04d}.png', f'{folder}/{idx:04d}.jpg')

        
if __name__ == "__main__":
    main()



