FROM nvcr.io/nvidia/pytorch:20.06-py3
RUN mkdir /root/datasets
RUN mkdir /root/datasets/localbot
RUN mkdir /root/models
RUN mkdir /root/models/localbot

RUN git clone https://github.com/DanielCoelho112/localization_end_to_end
ENV PYTHONPATH="/workspace/localization_end_to_end"
CMD ["sh", "-c", "cd localization_end_to_end && git pull"]


