#!/usr/bin/env python3

# stdlib
import sys
import argparse
import copy
import json

# 3rd-party
import rospy
from colorama import Fore, Style
from localbot_localization.src.dataset import LocalBotDataset
from localbot_localization.src.validate_dataset import ValidateDataset
import numpy as np
from localbot_core.src.utilities import *
from os.path import exists
import shutil


def main():
    parser = argparse.ArgumentParser(description='Validate dataset')
    parser.add_argument('-d', '--dataset', type=str,
                        required=True, help='Name of the dataset')


    arglist = [x for x in sys.argv[1:] if not x.startswith('__')]
    args = vars(parser.parse_args(args=arglist))

    dataset = LocalBotDataset(path_seq=args['dataset'])
    
    
    matrix44_frame2_world = np.loadtxt(f'{LocalBotDataset(dataset.getConfig()["raw"]).path_seq}/frame-00002.pose.txt', delimiter=',')
    
    for idx in range(len(dataset)):
        matrix44 = np.loadtxt(f'{dataset.path_seq}/frame-{idx:05d}.pose.txt', delimiter=',')
        
        # transform_matrix44_wrt0 to be w.r.t world
        matrix44_wrt_world = np.dot(matrix44_frame2_world, matrix44)
        write_transformation(filename=f'{dataset.path_seq}/frame-{idx:05d}.pose.txt', transformation=matrix44_wrt_world)
    
    
if __name__ == "__main__":
    main()
