#!/usr/bin/env python3

# stdlib
import sys
import argparse
import os

# 3rd-party
import rospkg
from localbot_core.src.utilities_ros import data2pose
import rospy
from colorama import Fore, Style
from std_msgs.msg import Header, ColorRGBA
from gazebo_msgs.srv import SetLightProperties, SetLightPropertiesRequest, GetLightProperties, GetLightPropertiesRequest
from geometry_msgs.msg import Point, Pose, Vector3, Quaternion
from visualization_msgs.msg import *
from localbot_core.src.interactive_data_collection import InteractiveDataCollection
from localbot_core.src.automatic_data_collection import AutomaticDataCollection



def main():
    
    rospy.init_node("set_lights")
        
    idx = 0
    att_quad = .1
    my_str = f'name: "user_point_light_{idx}" \nattenuation_quadratic: {att_quad}'
    
    print(my_str)
    
    with open('/tmp/set_light.txt', 'w') as f:
        f.write(my_str)
    
    os.system(f'gz topic -p /gazebo/room_024/light/modify -f /tmp/set_light.txt')
    



if __name__ == "__main__":
    main()



