#!/usr/bin/env python3

# stdlib
import sys
import argparse
import copy
import json

from regex import F

# 3rd-party
import rospy
from colorama import Fore, Style
from localbot_localization.src.dataset import LocalBotDataset
from localbot_localization.src.validate_dataset import ValidateDataset
import numpy as np
from localbot_core.src.utilities import *


def main():
    parser = argparse.ArgumentParser(description='Validate dataset')
    parser.add_argument('-p_sfm', '--poses_sfm', type=str,
                        required=True, help='Name of the dataset')

    arglist = [x for x in sys.argv[1:] if not x.startswith('__')]
    args = vars(parser.parse_args(args=arglist))

    p_sfm = f'/home/danc/datasets/localbot/meshroom/{args["poses_sfm"]}'
    
    first_frame = int(args['poses_sfm'].split('_')[-2])
    
    print(first_frame)

    matrix44_frame0_sfm = np.loadtxt(f'{p_sfm}/frame-{first_frame:05d}.pose.txt', delimiter=',')
    
    
    print(matrix44_frame0_sfm)
    
    size_dataset = sum(f.endswith('.txt') for f in os.listdir(p_sfm))
    
    print(size_dataset)
    
    for idx in range(size_dataset):
        idx2 = idx + first_frame
        print(idx2)
        matrix44 = np.loadtxt(f'{p_sfm}/frame-{idx2:05d}.pose.txt', delimiter=',')
        
        # transform matrix44 to be w.r.t. frame0
        matrix44_wrt_0 = np.dot(np.linalg.inv(matrix44_frame0_sfm), matrix44)
        
        
        write_transformation(filename=f'{p_sfm}/frame-{idx2:05d}.pose.txt', transformation=matrix44_wrt_0)
    
if __name__ == "__main__":
    main()
