#!/usr/bin/env python3

# stdlib
import sys
import argparse
import copy
import os

# 3rd-party
import rospy
from visualization_msgs.msg import *
from localbot_localization.src.dataset import LocalBotDataset
from localbot_localization.src.validate_dataset import ValidateDataset
import numpy as np
import shutil

def main():    
    parser = argparse.ArgumentParser(description='Validate dataset')
    parser.add_argument('-d', '--dataset', type=str, required=True, help='Name of the dataset')
    parser.add_argument('-if', '--image_folder', type=str, required=True, help='output folder')
    parser.add_argument('-nf', '--number_frames', type=int, required=True, help='number of frames to copy')
   
    arglist = [x for x in sys.argv[1:] if not x.startswith('__')]
    args = vars(parser.parse_args(args=arglist))
    
    nf = args['number_frames']
    dataset = LocalBotDataset(path_seq=args['dataset'])
    
    root_path = f'{os.environ["HOME"]}/datasets/localbot/{args["image_folder"]}' 

    
    poses = np.empty(shape=(nf,4,4))
    
    for idx in range(nf):
        matrix44 = np.loadtxt(f'{dataset.path_seq}/frame-{idx:05d}.pose.txt', delimiter=',')
        poses[idx,:,:] = matrix44
    np.savez(f'{root_path}/raw_poses.npz', c2w_mats=poses)
        
        
        

        

        
if __name__ == "__main__":
    main()



