#!/usr/bin/env python3

# stdlib
import sys
import argparse
import copy
import json

from regex import F

# 3rd-party
import rospy
from colorama import Fore, Style
from localbot_localization.src.dataset import Dataset
from localbot_localization.src.validate_dataset import ValidateDataset
import numpy as np
from localbot_core.src.utilities import *


def main():
    parser = argparse.ArgumentParser(description='Validate dataset')
    parser.add_argument('-f', '--folder', type=str,
                        required=True, help='Name of the dataset')
    parser.add_argument('-d', '--dataset', type=str,
                        required=True, help='Name of the dataset')

    arglist = [x for x in sys.argv[1:] if not x.startswith('__')]
    args = vars(parser.parse_args(args=arglist))

    dataset = Dataset(path_seq=args['dataset'])
    folder = f'/home/danc/datasets/localbot/mvg/output/{args["folder"]}'
    
    matrix44_frame0_world = np.loadtxt(f'{dataset.path_seq}/frame-00000.pose.txt', delimiter=',')
    
    size_dataset = sum(f.endswith('.txt') for f in os.listdir(folder))
    
    for idx in range(size_dataset):
        print(idx)
        
        matrix44 = np.loadtxt(f'{folder}/frame-{idx:05d}.pose.txt', delimiter=',')
        
        # transform matrix44 to be w.r.t. frame0
        matrix44_wrt_world = np.dot(matrix44_frame0_world, matrix44)
        
        
        write_transformation(filename=f'{folder}/frame-{idx:05d}.pose.txt', transformation=matrix44_wrt_world)
    
if __name__ == "__main__":
    main()
