#!/usr/bin/env python3

# stdlib
import sys
import argparse
import copy
import json


# 3rd-party
import rospy
from colorama import Fore, Style
from localbot_localization.src.dataset import LocalBotDataset
from localbot_localization.src.validate_dataset import ValidateDataset
import numpy as np
from localbot_core.src.utilities import *


def main():
    parser = argparse.ArgumentParser(description='sfm processing')
    parser.add_argument('-f', '--folder', type=str,
                        required=True, help='Name of the dataset')
    parser.add_argument('-i', '--input', type=str,
                        required=True, help='Name of the dataset')

    arglist = [x for x in sys.argv[1:] if not x.startswith('__')]
    args = vars(parser.parse_args(args=arglist))

    folder = f'/home/danc/datasets/localbot/meshroom/output/{args["folder"]}'
    input_file = f'/home/danc/datasets/localbot/meshroom/input/{args["input"]}'
    
    os.makedirs(folder)


    
    #TODO: CHANGE MANUALLY
    # find path
    
    #dirs =[i for i in os.walk(f"{p_sfm}")]

    # for each frame, we read the rotation, and translation. Transform into a 4x4 matrix and save it as txt.
    file = json.load(open(input_file))
    
    # create mappings betwenn frame idx and pose idx
    maps = {} # key: pose_id, value: frame id
    
    for view in file['views']:
        frame_name = view['path'].split('/')[-1]
        pose_id = view['poseId']
        maps[pose_id] = frame_name
    
    for pose in file['poses']:
        pose_id = pose['poseId']
        frame_idx = int(maps[pose_id].split('.')[0])
        
        
        rotation = np.array(pose['pose']['transform']['rotation'])
        rotation33 = np.empty(shape=(3,3))
        
        #rotation33[:,0] =  rotation[0:3]
        #rotation33[:,1] =  rotation[3:6]
        #rotation33[:,2] =  rotation[6:9]
        
        rotation33[0,:] =  rotation[0:3]
        rotation33[1,:] =  rotation[3:6]
        rotation33[2,:] =  rotation[6:9]
        
        translation = np.array(pose['pose']['transform']['center'])
        
        matrix44 = rotationAndpositionToMatrix44(rotation33, translation)
        
        
        write_transformation(filename=f'{folder}/frame-{frame_idx:05d}.pose.txt', transformation=matrix44)
    
    
if __name__ == "__main__":
    main()
