#!/usr/bin/env python3

# stdlib
import sys
import argparse
import numpy as np
import os
import matplotlib.pyplot as plt
import yaml
from yaml.loader import SafeLoader


def main():    
    parser = argparse.ArgumentParser(description='Validate dataset')
    parser.add_argument('-model_folder', '--model_folder', type=str, required=True, help='Model folder, e.g. pointnet1')

    arglist = [x for x in sys.argv[1:] if not x.startswith('__')]
    args = vars(parser.parse_args(args=arglist))
    
    folder = f'{os.environ["HOME"]}/models/localbot/{args["model_folder"]}'
    
    with open(f'{folder}/config.yaml') as f:
            config = yaml.load(f, Loader=SafeLoader) 
            
    
    train_losses = config['train_losses']
    test_losses = config['test_losses']
    
    plt.plot(train_losses, label='train loss')
    plt.plot(test_losses, label='test loss')
    plt.legend()
    #plt.show()
    
    
    plt.savefig(f'{folder}/losses.png')

            
if __name__ == "__main__":
    main()



