#!/usr/bin/env python3

import cv2
import torch.utils.data as data
from localbot_core.src.utilities import read_pcd, matrixToXYZ, matrixToQuaternion
from localbot_localization.src.utilities import normalize_quat
import numpy as np
import torch
import os

from localbot_localization.src.dataset import LocalBotDataset, LocalBotDatasetDepth


def main():

    # load depth image

    dataset = LocalBotDataset('seq_depth_test_depth_std1')


    for idx in range(len(dataset)):
        print(idx)
        
        cv_image = np.load(f'{dataset.path_seq}/frame-{idx:05d}.depth.npy').astype(np.float32)
        
        cv2.imshow('image', cv_image)
        cv2.waitKey(0)

        
if __name__ == "__main__":
    main()
